config/routes.rb
SoftwareManager::Application.routes.draw do
  post "auth/:provider/callback" => "auth#create"
  get "unauthorized" => "auth#unauthorized", as: :unauthorized
  match 'logout' => 'application#logout', via: [:get, :post]

  resources :licenses, only: [:index] do
    resources :allocations

    collection do
      get 'owned' => 'licenses#user_license', as: :owned
    end
  end

  resources :operating_systems

  scope ':os' do
    get 'softwares' => 'softwares#index', as: :os_software
  end

  resources :softwares do
    member do
      get 'download'
    end
    resources :licenses do
      collection do
        get 'owned' => 'licenses#user_license'
      end
    end

    resources :requests, except: [:index] do
      member do
        post 'approve'
      end
    end
  end

  resources :requests, only: [:index]
  resources :users

  root 'application#home'

end

app/controllers/licenses_controller.rb
class LicensesController < ApplicationController
  include Authenticable

  before_action :set_software, except: [:index, :user_license]
  before_action :set_license, only: [:show, :edit, :update, :destroy]

  # GET /licenses
  # GET /licenses.json
  def index
    context = params[:software_id] ? set_software.licenses : License
    @licenses = context.all
  end

  def user_license
    licenses = current_user.licenses
    @licenses =  params[:software_id] ? licenses.where(software_id: set_software.id) : licenses
  end

  # GET /licenses/1
  # GET /licenses/1.json
  def show
  end

  # GET /licenses/new
  def new
    @license = @software.licenses.build
  end

  # GET /licenses/1/edit
  def edit
  end

  # POST /licenses
  # POST /licenses.json
  def create
    @license = @software.licenses.new(license_params)

    respond_to do |format|
      if @license.save
        format.html { redirect_to software_license_path(@software, @license), notice: 'License was successfully created.' }
        format.json { render action: 'show', status: :created, location: @license }
      else
        format.html { render action: 'new' }
        format.json { render json: @license.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /licenses/1
  # PATCH/PUT /licenses/1.json
  def update
    respond_to do |format|
      if @license.update(license_params)
        format.html { redirect_to software_license_path(@software, @license), notice: 'License was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @license.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /licenses/1
  # DELETE /licenses/1.json
  def destroy
    @license.state = :inactive
    @license.save
    respond_to do |format|
      format.html { redirect_to software_licenses_url(@software) }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_license
      @license = @software.licenses.find(params[:id])
    end

    def set_software
      @software = Software.find(params[:software_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def license_params
      params.require(:license).permit(:software_id, :license_user, :license, :user_count, :purchase_date, :cost, :state)
    end
end

app/helpers/licenses_helper.rb
module LicensesHelper
end

app/views/licenses/_form.html.erb
<%= form_for([@software, @license]) do |f| %>
  <% if @license.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@license.errors.count, "error") %> prohibited this license from being saved:</h2>

      <ul>
      <% @license.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :license_user %><br>
    <%= f.text_field :license_user %>
  </div>
  <div class="field">
    <%= f.label :license %><br>
    <%= f.text_area :license %>
  </div>
  <div class="field">
    <%= f.label :user_count %><br>
    <%= f.number_field :user_count %>
  </div>
  <div class="field">
    <%= f.label :purchase_date %><br>
    <%= f.date_select :purchase_date %>
  </div>
  <div class="field">
    <%= f.label :cost %><br>
    <%= f.number_field :cost %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.select :state, License::STATE %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/licenses/_owned_licenses.html.erb
<% if licenses.count > 0 %>
<table id="ownedLicenses">
  <thead>
  <tr>
    <th>Software</th>
    <th>License user</th>
    <th>License</th>
    <th>Cost</th>
  </tr>
  </thead>

  <tbody>
  <% licenses.each do |license| %>
      <% license.allocations.each do |allocation| %>
          <tr>
            <td><%= license.software.name %>  </td>
            <td><%= license.license_user %>  </td>
            <td><%= license.license %>  </td>
            <td>$<%= license.cost / license.user_count %></td>
          </tr>
      <% end %>
  <% end %>
  </tbody>
</table>
<% else %>
    <%= alert_warning 'You donot own any license' %>
<% end %>

app/views/licenses/edit.html.erb
<h1>Editing license</h1>

<%= render 'form' %>

<%= link_to 'Show', software_license_path(@software, @license) %> |
<%= link_to 'Back', software_licenses_path(@software) %>

app/views/licenses/index.html.erb
<div class="page">
<%= link_to_back %>

<h1>Listing licenses</h1>

<table>
  <thead>
    <tr>
      <th>Software</th>
      <th>License user</th>
      <th>License</th>
      <th>User count</th>
      <th>Allocation count</th>
      <th>Purchase date</th>
      <th>Cost</th>
      <th>state</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @licenses.each do |license| %>
      <tr>
        <td><%= license.software.name %>  </td>
        <td><%= link_to license.license_user, software_license_path(license.software, license) %>  </td>
        <td><%= link_to license.license, software_license_path(license.software, license) %>  </td>
        <td><%= license.user_count %>  </td>
        <td><%= link_to license.used_count, software_license_path(license.software, license) %>  </td>
        <td><%= license.purchase_date %></td>
        <td><%= license.cost %></td>
        <td><% if license.active? %><span class="label label-success">Active</span><%else%><span class="label label-danger">Inactive</span><%end%></td>
        <td><%= link_to_edit edit_software_license_path(license.software, license) %></td>
        <td><%= link_to_destroy software_license_path(license.software, license) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if current_user.can?(:licenses, :new) && @software%>
    <%= link_to 'New License', new_software_license_path(@software) %>
<%end%>

    </div>

app/views/licenses/new.html.erb
<h1>New license</h1>

<%= render 'form' %>

<%= link_to 'Back', software_licenses_path(@software) %>

app/views/licenses/show.html.erb
<div class="page">
  <%= link_to_back %>
<p>
  <strong>Software:</strong>
  <%= link_to @software.name, @software %>
</p>

<p>
  <strong>License user:</strong>
  <%= @license.license_user %>
</p>

<p>
  <strong>License:</strong>
  <%= @license.license %>
</p>

<p>
  <strong>User count:</strong>
  <%= @license.user_count %>
</p>

<p>
  <strong>Purchase date:</strong>
  <%= @license.purchase_date %>
</p>

<p>
  <strong>Cost:</strong>
  <%= @license.cost %>
</p>

<p>
  <strong>Allocated Count:</strong>
  <%= @license.used_count %>
</p>


<p>
  <strong>State:</strong>
  <% if @license.active? %><span class="label label-success">Active</span><%else%><span class="label label-danger">Inactive</span><%end%>
</p>

<%= link_to 'Allocate', new_license_allocation_path(@license), class: 'btn btn-default' %>
<%= link_to_edit edit_software_license_path(@software, @license) %>

<h1>Listing allocations</h1>

<table>
  <thead>
  <tr>
    <th>Software</th>
    <th>License</th>
    <th>User</th>
    <th>Project code</th>
    <th>State</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
  </thead>

  <tbody>
  <% @license.allocations.each do |allocation| %>
      <tr>
        <td><%= link_to allocation.license.software.name, allocation.license.software %></td>
        <td><%= allocation.license_id %></td>
        <td><%= allocation.user.name %> (<%=allocation.user.email%>) </td>
        <td><%= allocation.project_code %></td>
        <td><% if allocation.active? %><span class="label label-success">Active</span><%else%><span class="label label-danger">Inactive</span><%end%></td>
        <td><%= link_to 'Show', license_allocation_path(@license, allocation) %></td>
        <td><%= link_to_edit edit_license_allocation_path(@license, allocation) %></td>
        <td><%= link_to_destroy license_allocation_path(@license, allocation) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

    </div>

app/views/licenses/user_license.html.erb
<div id="userLicensePage" class="page">
  <%= link_to_back %>

  <% if @software %>
  <h1>License for <%= @software.name %></h1>
  <%else%>
  <h1>Owned Licenses</h1>
  <%end%>

  <%= render partial: 'owned_licenses', locals: {licenses: @licenses} %>
</div>