config/routes.rb
SoftwareManager::Application.routes.draw do
  post "auth/:provider/callback" => "auth#create"
  get "unauthorized" => "auth#unauthorized", as: :unauthorized
  match 'logout' => 'application#logout', via: [:get, :post]

  resources :licenses, only: [:index] do
    resources :allocations

    collection do
      get 'owned' => 'licenses#user_license', as: :owned
    end
  end

  resources :operating_systems

  scope ':os' do
    get 'softwares' => 'softwares#index', as: :os_software
  end

  resources :softwares do
    member do
      get 'download'
    end
    resources :licenses do
      collection do
        get 'owned' => 'licenses#user_license'
      end
    end

    resources :requests, except: [:index] do
      member do
        post 'approve'
      end
    end
  end

  resources :requests, only: [:index]
  resources :users

  root 'application#home'

end

app/models/allocation.rb
class Allocation < ActiveRecord::Base
  STATE = [:active, :inactive]
  include Stateful

  belongs_to :license
  belongs_to :user

  validates :license, :user, presence: true
  validate :license_availability

  after_create :notify_create

  def license_availability
    errors.add(:license, 'unavailable for allocation') unless self.license.available? if self.license
  end

  def self.build(request, license)
    instance = new
    instance.update(license: license, user: request.user, project_code: request.project_code, state: :active)
    instance
  end

  private

  def notify_create
    LicenseMailer.request_accepted(self).deliver
  end
end

app/controllers/allocations_controller.rb
class AllocationsController < ApplicationController
  include Authenticable

  before_action :set_license
  before_action :set_allocation, only: [:show, :edit, :update, :destroy]

  # GET /allocations
  # GET /allocations.json
  def index
    @allocations = @license.allocations.all
  end

  # GET /allocations/1
  # GET /allocations/1.json
  def show
  end

  # GET /allocations/new
  def new
    @allocation = @license.allocations.build
  end

  # GET /allocations/1/edit
  def edit
  end

  # POST /allocations
  # POST /allocations.json
  def create
    @allocation = @license.allocations.new(allocation_params)
    @allocation.state = :active

    respond_to do |format|
      if @allocation.save
        format.html { redirect_to license_allocation_path(@license, @allocation), notice: 'Allocation was successfully created.' }
        format.json { render action: 'show', status: :created, location: @allocation }
      else
        format.html { render action: 'new' }
        format.json { render json: @allocation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /allocations/1
  # PATCH/PUT /allocations/1.json
  def update
    respond_to do |format|
      if @allocation.update(allocation_params)
        format.html { redirect_to license_allocation_path(@license, @allocation), notice: 'Allocation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @allocation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /allocations/1
  # DELETE /allocations/1.json
  def destroy
    @allocation.state = 'inactive'
    @allocation.save
    url = can?(:index) ? license_allocations_path(@license) : softwares_path
    respond_to do |format|
      format.html { redirect_to url, notice: 'License returned successfully.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_allocation
      @allocation = @license.allocations.find(params[:id])
    end

 # Use callbacks to share common setup or constraints between actions.
    def set_license
      @license = License.find(params[:license_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def allocation_params
      params.require(:allocation).permit(:license_id, :user_id, :project_code, :state)
    end
end

app/helpers/allocations_helper.rb
module AllocationsHelper
end

app/views/allocations/_form.html.erb
<%= form_for([@license, @allocation]) do |f| %>
  <% if @allocation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@allocation.errors.count, "error") %> prohibited this allocation from being saved:</h2>

      <ul>
      <% @allocation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :project_code %><br>
    <%= f.text_field :project_code %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.select :state, Allocation::STATE %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/allocations/edit.html.erb
<h1>Editing allocation</h1>

<%= render 'form' %>

<%= link_to 'Show', license_allocation_path(@license, @allocation) %> |
<%= link_to 'Back', license_allocations_path(@license) %>

app/views/allocations/index.csv.erb
<%- headers = ["Id", "License User", "User", "Project Code"] -%>
<%= CSV.generate_line headers %>
<%- @allocations.each do |n| -%>
    <%- row = [ n.id, n.license.license_user, n.user.name, n.project_code] -%>
    <%= CSV.generate_line row, :row_sep => ?\t, :quote_char => ?\ %>
<%- end -%>

app/views/allocations/index.html.erb
<h1>Listing allocations</h1>
<p>
  Download:
  <%= link_to "CSV", license_allocations_path(format: "csv") %>
</p>
<table>
  <thead>
    <tr>
      <th>Software</th>
      <th>License</th>
      <th>User</th>
      <th>Project code</th>
      <th>State</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @allocations.each do |allocation| %>
      <tr>
        <td><%= link_to allocation.license.software.name, allocation.license.software %></td>
        <td><%= link_to allocation.license.license_user, software_license_path(@license.software, @license) %></td>
        <td><%= allocation.user.name %></td>
        <td><%= allocation.project_code %></td>
        <td><% if allocation.active? %><span class="label label-success">Active</span><%else%><span class="label label-danger">Inactive</span><%end%></td>
        <td><%= link_to 'Show', license_allocation_path(@license, allocation) %></td>
        <td><%= link_to 'Edit', edit_license_allocation_path(@license, allocation) %></td>
        <td><%= link_to 'Destroy', license_allocation_path(@license, allocation), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Allocation', new_license_allocation_path(@license) %>

app/views/allocations/new.html.erb
<h1>New allocation</h1>

<%= render 'form' %>

<%= link_to 'Back', license_allocations_path(@license) %>

app/views/allocations/show.html.erb
<p>
  <strong>License:</strong>
  <%= @allocation.license_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @allocation.user.name %>
</p>

<p>
  <strong>Project code:</strong>
  <%= @allocation.project_code %>
</p>

<%= link_to 'Edit', edit_license_allocation_path(@license, @allocation) %> |
<%= link_to 'Back', license_allocations_path(@license) %>