config/routes.rb
SoftwareManager::Application.routes.draw do
  post "auth/:provider/callback" => "auth#create"
  get "unauthorized" => "auth#unauthorized", as: :unauthorized
  match 'logout' => 'application#logout', via: [:get, :post]

  resources :licenses, only: [:index] do
    resources :allocations

    collection do
      get 'owned' => 'licenses#user_license', as: :owned
    end
  end

  resources :operating_systems

  scope ':os' do
    get 'softwares' => 'softwares#index', as: :os_software
  end

  resources :softwares do
    member do
      get 'download'
    end
    resources :licenses do
      collection do
        get 'owned' => 'licenses#user_license'
      end
    end

    resources :requests, except: [:index] do
      member do
        post 'approve'
      end
    end
  end

  resources :requests, only: [:index]
  resources :users

  root 'application#home'

end

app/models/operating_system.rb
class OperatingSystem < ActiveRecord::Base
  has_many :softwares
end

app/controllers/operating_systems_controller.rb
class OperatingSystemsController < ApplicationController
  include Authenticable

  before_action :set_operating_system, only: [:show, :edit, :update, :destroy]

  # GET /operating_systems
  # GET /operating_systems.json
  def index
    @operating_systems = OperatingSystem.all
  end

  # GET /operating_systems/1
  # GET /operating_systems/1.json
  def show
  end

  # GET /operating_systems/new
  def new
    @operating_system = OperatingSystem.new
  end

  # GET /operating_systems/1/edit
  def edit
  end

  # POST /operating_systems
  # POST /operating_systems.json
  def create
    @operating_system = OperatingSystem.new(operating_system_params)

    respond_to do |format|
      if @operating_system.save
        format.html { redirect_to @operating_system, notice: 'Operating system was successfully created.' }
        format.json { render action: 'show', status: :created, location: @operating_system }
      else
        format.html { render action: 'new' }
        format.json { render json: @operating_system.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /operating_systems/1
  # PATCH/PUT /operating_systems/1.json
  def update
    respond_to do |format|
      if @operating_system.update(operating_system_params)
        format.html { redirect_to @operating_system, notice: 'Operating system was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @operating_system.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /operating_systems/1
  # DELETE /operating_systems/1.json
  def destroy
    @operating_system.destroy
    respond_to do |format|
      format.html { redirect_to operating_systems_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_operating_system
      @operating_system = OperatingSystem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def operating_system_params
      params.require(:operating_system).permit(:name)
    end
end

app/helpers/operating_systems_helper.rb
module OperatingSystemsHelper
end

app/views/operating_systems/_form.html.erb
<%= form_for(@operating_system) do |f| %>
  <% if @operating_system.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@operating_system.errors.count, "error") %> prohibited this operating_system from being saved:</h2>

      <ul>
      <% @operating_system.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/operating_systems/edit.html.erb
<h1>Editing operating_system</h1>

<%= render 'form' %>

<%= link_to 'Show', @operating_system %> |
<%= link_to 'Back', operating_systems_path %>

app/views/operating_systems/index.html.erb
<h1>Listing operating_systems</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @operating_systems.each do |operating_system| %>
      <tr>
        <td><%= operating_system.name %></td>
        <td><%= link_to 'Show', operating_system %></td>
        <td><%= link_to 'Edit', edit_operating_system_path(operating_system) %></td>
        <td><%= link_to 'Destroy', operating_system, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Operating system', new_operating_system_path %>

app/views/operating_systems/new.html.erb
<h1>New operating_system</h1>

<%= render 'form' %>

<%= link_to 'Back', operating_systems_path %>

app/views/operating_systems/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @operating_system.name %>
</p>

<%= link_to 'Edit', edit_operating_system_path(@operating_system) %> |
<%= link_to 'Back', operating_systems_path %>