config/routes.rb
SoftwareManager::Application.routes.draw do
  post "auth/:provider/callback" => "auth#create"
  get "unauthorized" => "auth#unauthorized", as: :unauthorized
  match 'logout' => 'application#logout', via: [:get, :post]

  resources :licenses, only: [:index] do
    resources :allocations

    collection do
      get 'owned' => 'licenses#user_license', as: :owned
    end
  end

  resources :operating_systems

  scope ':os' do
    get 'softwares' => 'softwares#index', as: :os_software
  end

  resources :softwares do
    member do
      get 'download'
    end
    resources :licenses do
      collection do
        get 'owned' => 'licenses#user_license'
      end
    end

    resources :requests, except: [:index] do
      member do
        post 'approve'
      end
    end
  end

  resources :requests, only: [:index]
  resources :users

  root 'application#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include Authenticable

  def home
  end

  def logout
    CASClient::Frameworks::Rails::Filter.logout(self)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_to_back(url=:back)
    link_to '<i class="glyphicon glyphicon-circle-arrow-left"></i><span>Back</span>'.html_safe, url, class: "btn btn-default"
  end

  def link_to_home
    link_to '<i class="glyphicon glyphicon-home"></i><span>Home</span>'.html_safe, '/', class: "btn btn-default"
  end

  def link_to_destroy(url, message='Are you sure?')
    link_to '<i class="glyphicon glyphicon-trash"></i><span>Destroy</span>'.html_safe , url, method: :delete, data: { confirm: message }, class: 'btn btn-danger'
  end

  def link_to_download(software)
    link_to '<i class="glyphicon glyphicon-download"></i><span>Download</span>'.html_safe, download_software_path(software), class: "btn btn-success download-software"
  end

  def link_to_request_access(software)
    if current_user.requests.where(software_id: software.id).count > 0
      link_to '<i class="glyphicon glyphicon-time"></i><span>Waiting</span>'.html_safe, '', class: "btn btn-default"
    else
      link_to '<i class="glyphicon glyphicon-lock"></i><span>Request</span>'.html_safe, new_software_request_path(software), class: "btn btn-warning"
    end
  end

  def link_to_edit(object)
    link_to '<i class="glyphicon glyphicon-pencil"></i><span>Edit</span>'.html_safe, object, class: "btn btn-default"
  end

  def link_to_licenses(software)
    link_to '<i class="glyphicon glyphicon-book"></i><span>Licenses</span>'.html_safe, software_licenses_path(software), class: "btn btn-default"
  end

  def alert_warning(message)
    ('<div class="alert alert-warning">
      <i class="glyphicon glyphicon-exclamation-sign"></i><span>'+message+'</span>
    </div>').html_safe
  end
end

app/views/application/home.html.erb
<div id="Dashboard" class="page">
    <div class="widget-container">
        <% if current_user.can?(:requests, :view_all) %>
        <a class="widget widget-small" href="<%= requests_path %>">
            <div class="widget-main-area"><%= Request.count %></div>
            <div class="widget-footer">New Requests</div>
        </a>
      <% else %>
      <a class="widget widget-small" href="<%= requests_path %>">
        <div class="widget-main-area"><%= current_user.requests.count %></div>
        <div class="widget-footer">My Requests</div>
      </a>
      <% end %>

      <a class="widget widget-small" href="<%= softwares_path %>">
        <div class="widget-main-area"><%= Software.count %></div>
        <div class="widget-footer">Softwares</div>
      </a>
      <% if current_user.can?(:licenses, :index) %>
      <a class="widget widget-small" href="<%= licenses_path %>">
        <div class="widget-main-area"><%= License.count %></div>
        <div class="widget-footer">Licenses</div>
      </a>
      <%end%>
      <a class="widget widget-small" href="<%= owned_licenses_path %>">
        <div class="widget-main-area"><%= current_user.licenses.count %></div>
        <div class="widget-footer">My Licenses</div>
      </a>
      <% if current_user.can?(:users, :index) %>
     <a class="widget widget-small" href="<%= users_path %>">
        <div class="widget-main-area"><%= User.count %></div>
        <div class="widget-footer">Users</div>
      </a>
          <% end %>
    </div>

    <% if current_user.can?(:softwares, :view_unapproved) %>
    <div class="widget-container">
        <div class="widget-container-header">Software Stats</div>
        <% Software::STATE.each do |state| %>
            <a class="widget widget-small" href="<%= softwares_path(state: state)%>">
                <div class="widget-main-area"><%= Software.where(state: state).count %></div>
                <div class="widget-footer"><%= state %></div>
            </a>
        <% end %>
    </div>
    <%end%>

    <div class="widget-container">
        <div class="widget-container-header">Software OS Breakdown</div>
        <% OperatingSystem.all.each do |os| %>
            <a class="widget widget-small" href="<%= os_software_path(os: os.name.downcase) %>">
                <div class="widget-main-area"><%= os.softwares.count %></div>
                <div class="widget-footer"><%= os.name %></div>
            </a>
        <% end %>
    </div>
</div>